### ISSUE TITLE
Database Rollback Not Triggered on Exception

### ISSUE THREAD

**Issue by WAZIRI123** [leafsphp/db#26]
##  Description
I am encountering an issue where database transactions are not rolling back when an exception occurs,  which i think it may be a bug in the framework . Specifically, I am using db()->beginTransaction() to start a transaction, when an exception is thrown within the try block, the db()->rollBack() call in the catch block is not triggered, and the changes made within the transaction are still committed.

## Steps to reproduce the behavior:
1. Start a transaction with db()->beginTransaction().
2. Perform multiple database operations inside a try block.
3. Throw an exception within the try block (e.g., manually throw an exception or allow an error to occur).
4. Call db()->rollBack() in the catch block.
5. Check the database and observe that the changes have been committed instead of being rolled back.

## Expected behavior
When an exception is thrown within a transaction, the db()->rollBack() function should be called, and no changes made within the transaction should be committed to the database. All changes should be undone.

## Additional context
code sample:
`public function addProject()
{
    db()->beginTransaction(); // Start the transaction

    try {
        // Simulate some database operations (e.g., creating a project)
        $project = Project::create([
            'name' => 'Test Project',
            'client_id' => 1,
        ]);

        // Intentionally throw an exception
        throw new \Exception("Simulated error");

        // Commit the transaction (won't be reached due to the exception)
        db()->commit();

    } catch (\Exception $e) {
        // Rollback the transaction on error
        db()->rollBack();

        // Return the error message for debugging
        return response()->json([
            'status' => 'error',
            'message' => 'An error occurred: ' . $e->getMessage(),
        ]);
    }
}

`
environment :
Leaf version: 3.3v
PHP : 8.3.6v

**Comment by mychidarko** [comment]
I'll try to replicate this issue

**Comment by ibnsultan** [comment]
@WAZIRI123 transactions only work with queries associated with \Leaf\DB module i.e `db()->query("SQL STATEMENT)->execute()` your preceding query is based of eloquent ORM which is layered through the `mvc-core` module through `Leaf\Database` namespace

When workig with transactions \Leaf\Db
```php
// instead of  (this E-ORM Query, not related to \Leaf\Db)
$project = Project::create([
     'name' => 'Project',
     'client_id' => 1,
 ]);
 
 // try
db()->insert('projects')
  ->params(['name' => 'Project', 'clientId'=>1])
  ->execute();

// or try
db()->query('INSERT INTO projects (name, client_id) VALUES (?, ?)')
    ->bind('Project', 1)
    ->execute();
```

In that case the rollback is not likely to go through as they are two different connection instances.

ps: 
- [`Leaf\DB`](https://leafphp.dev/docs/database/#leaf-db) and `Leaf\Database` are very different, each has nothing to do with another
- elequent ORM transactions in leaf also have bit of an issue, we're working on them.

cc: @mychidarko

**Comment by WAZIRI123** [comment]
Thank you, @ibnsultan. I tested it that way, and it's working now.
